version: '3.9'
services:
  web:
    build: .
    command: python /lvlup_python/manage.py runserver 0.0.0.0:8000
    env_file: 
      - dev.env
    volumes:
      - .:/lvlup_python
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}" 
volumes:
  postgres_data:
