# Generated by Django 4.1.4 on 2022-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
