# Generated by Django 4.1.4 on 2022-12-08 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calc_app", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calc_app.category",
            ),
        ),
    ]
